from pathlib import Path

page_path = Path("src/pages/MqsPrototype.tsx")
test_path = Path("tests/mqs-prototype.spec.ts")

page = page_path.read_text()
tests = test_path.read_text()

old_import = '''  Send,\n  Shuffle,\n  Trash2,\n  Upload,\n  WifiOff,\n'''
new_import = '''  Send,\n  Shuffle,\n  SkipForward,\n  Trash2,\n  Upload,\n  Volume2,\n  VolumeX,\n  WifiOff,\n'''
if old_import not in page:
    raise SystemExit("icon import anchor not found")
page = page.replace(old_import, new_import, 1)

old_state = '''  const [pendingSetlist, setPendingSetlist] =\n    React.useState<PendingSetlist | null>(null)\n  const [stopOpen, setStopOpen] = React.useState(false)\n  const [dragSource, setDragSource] = React.useState<string | null>(null)\n'''
new_state = '''  const [pendingSetlist, setPendingSetlist] =\n    React.useState<PendingSetlist | null>(null)\n  const [stopOpen, setStopOpen] = React.useState(false)\n  const [localMuted, setLocalMuted] = React.useState(false)\n  const [localVolume, setLocalVolume] = React.useState(100)\n  const [volumeOpen, setVolumeOpen] = React.useState(false)\n  const [volumeDraft, setVolumeDraft] = React.useState(100)\n  const [dragSource, setDragSource] = React.useState<string | null>(null)\n'''
if old_state not in page:
    raise SystemExit("local audio state anchor not found")
page = page.replace(old_state, new_state, 1)

old_stop = '''  function stopAndClear() {\n    setPlayed([])\n    setCurrent(null)\n    setUpcoming([])\n    setElapsed(0)\n    setIsPlaying(false)\n    setStopOpen(false)\n  }\n\n  if (!windowOpen) return null\n'''
new_stop = '''  function stopAndClear() {\n    setPlayed([])\n    setCurrent(null)\n    setUpcoming([])\n    setElapsed(0)\n    setIsPlaying(false)\n    setStopOpen(false)\n  }\n\n  function openLocalVolume() {\n    setVolumeDraft(localVolume)\n    setVolumeOpen(true)\n  }\n\n  function applyLocalVolume() {\n    const next = Math.max(0, Math.min(100, Math.round(volumeDraft)))\n    setLocalVolume(next)\n    setVolumeOpen(false)\n  }\n\n  if (!windowOpen) return null\n'''
if old_stop not in page:
    raise SystemExit("local audio function anchor not found")
page = page.replace(old_stop, new_stop, 1)

old_card = '''        data-testid="mqs-modal"\n        data-connection-state={connectionState}\n        aria-busy={connectionBlocked || undefined}\n'''
new_card = '''        data-testid="mqs-modal"\n        data-connection-state={connectionState}\n        data-local-muted={localMuted ? "true" : "false"}\n        data-local-volume={localVolume}\n        aria-busy={connectionBlocked || undefined}\n'''
if old_card not in page:
    raise SystemExit("modal state anchor not found")
page = page.replace(old_card, new_card, 1)

old_menu = '''              <DropdownMenuContent align="end" className="w-56">\n                <DropdownMenuItem\n                  disabled={!url.trim()}\n                  onSelect={() => addUrl("tail")}\n                >\n                  Add pasted URL\n                </DropdownMenuItem>\n                <DropdownMenuItem\n                  disabled={!url.trim()}\n                  onSelect={() => addUrl("next")}\n                >\n                  Play pasted URL next\n                </DropdownMenuItem>\n                <DropdownMenuSeparator />\n                <DropdownMenuItem\n                  onSelect={() => fileInputRef.current?.click()}\n                >\n                  <Upload />\n                  Upload setlist\n                </DropdownMenuItem>\n                <DropdownMenuItem\n                  disabled={upcoming.length < 2}\n                  onSelect={() =>\n                    setUpcoming((items) =>\n                      [...items].sort(() => Math.random() - 0.5)\n                    )\n                  }\n                >\n                  <Shuffle />\n                  Shuffle upcoming\n                </DropdownMenuItem>\n                <DropdownMenuSeparator />\n                <DropdownMenuItem\n                  disabled={upcoming.length === 0}\n                  onSelect={() => setUpcoming([])}\n                >\n                  <Trash2 />\n                  Clear upcoming\n                </DropdownMenuItem>\n                <DropdownMenuItem\n                  variant="destructive"\n                  disabled={\n                    !current && upcoming.length === 0 && played.length === 0\n                  }\n                  onSelect={() => setStopOpen(true)}\n                >\n                  <Trash2 />\n                  Stop & clear all\n                </DropdownMenuItem>\n              </DropdownMenuContent>\n'''
new_menu = '''              <DropdownMenuContent align="end" className="w-56">\n                {url.trim() ? (\n                  <>\n                    <DropdownMenuItem onSelect={() => addUrl("next")}>\n                      <SkipForward />\n                      Play pasted URL next\n                    </DropdownMenuItem>\n                    <DropdownMenuSeparator />\n                  </>\n                ) : null}\n                <DropdownMenuItem\n                  onSelect={() => fileInputRef.current?.click()}\n                >\n                  <Upload />\n                  Load setlist\n                </DropdownMenuItem>\n                <DropdownMenuItem\n                  disabled={upcoming.length < 2}\n                  onSelect={() =>\n                    setUpcoming((items) =>\n                      [...items].sort(() => Math.random() - 0.5)\n                    )\n                  }\n                >\n                  <Shuffle />\n                  Shuffle upcoming\n                </DropdownMenuItem>\n                <DropdownMenuItem\n                  onSelect={() => setLocalMuted((value) => !value)}\n                >\n                  {localMuted ? <Volume2 /> : <VolumeX />}\n                  {localMuted ? "Unmute local audio" : "Mute local audio"}\n                </DropdownMenuItem>\n                <DropdownMenuItem onSelect={openLocalVolume}>\n                  <Volume2 />\n                  Set local volume…\n                </DropdownMenuItem>\n                <DropdownMenuSeparator />\n                <DropdownMenuItem\n                  variant="destructive"\n                  disabled={upcoming.length === 0}\n                  onSelect={() => setUpcoming([])}\n                >\n                  <Trash2 />\n                  Clear upcoming\n                </DropdownMenuItem>\n                <DropdownMenuItem\n                  variant="destructive"\n                  disabled={\n                    !current && upcoming.length === 0 && played.length === 0\n                  }\n                  onSelect={() => setStopOpen(true)}\n                >\n                  <Trash2 />\n                  Stop & clear all\n                </DropdownMenuItem>\n              </DropdownMenuContent>\n'''
if old_menu not in page:
    raise SystemExit("secondary actions menu anchor not found")
page = page.replace(old_menu, new_menu, 1)

old_stop_dialog = '''      <Dialog open={stopOpen} onOpenChange={setStopOpen}>\n'''
volume_dialog = '''      <Dialog\n        open={volumeOpen}\n        onOpenChange={(open) => {\n          setVolumeOpen(open)\n          if (open) setVolumeDraft(localVolume)\n        }}\n      >\n        <DialogContent>\n          <DialogHeader>\n            <DialogTitle>Local audio volume</DialogTitle>\n            <DialogDescription>\n              This changes MQS audio on this device only. It does not affect\n              room volume.\n            </DialogDescription>\n          </DialogHeader>\n          <div className="flex items-center gap-3 py-2">\n            <Volume2\n              className="size-4 shrink-0 text-muted-foreground"\n              aria-hidden="true"\n            />\n            <input\n              data-testid="local-volume-slider"\n              type="range"\n              min={0}\n              max={100}\n              step={1}\n              value={volumeDraft}\n              aria-label="Local audio volume"\n              onChange={(event) => setVolumeDraft(Number(event.target.value))}\n              className="h-2 min-w-0 flex-1 cursor-pointer accent-primary"\n            />\n            <span\n              data-testid="local-volume-value"\n              className="w-10 text-right text-sm text-muted-foreground tabular-nums"\n            >\n              {volumeDraft}%\n            </span>\n          </div>\n          <DialogFooter>\n            <Button variant="outline" onClick={() => setVolumeOpen(false)}>\n              Cancel\n            </Button>\n            <Button onClick={applyLocalVolume}>Apply volume</Button>\n          </DialogFooter>\n        </DialogContent>\n      </Dialog>\n\n      <Dialog open={stopOpen} onOpenChange={setStopOpen}>\n'''
if old_stop_dialog not in page:
    raise SystemExit("volume dialog insertion anchor not found")
page = page.replace(old_stop_dialog, volume_dialog, 1)

old_menu_expect = '''    await page.getByRole("button", { name: "Queue actions" }).click()\n    await expect(\n      page.getByRole("menuitem", { name: "Upload setlist" })\n    ).toBeVisible()\n    await expect(\n      page.getByRole("menuitem", { name: "Shuffle upcoming" })\n    ).toBeVisible()\n    await expect(\n      page.getByRole("menuitem", { name: "Clear upcoming" })\n    ).toBeVisible()\n'''
new_menu_expect = '''    await page.getByRole("button", { name: "Queue actions" }).click()\n    await expect(\n      page.getByRole("menuitem", { name: "Load setlist" })\n    ).toBeVisible()\n    await expect(\n      page.getByRole("menuitem", { name: "Shuffle upcoming" })\n    ).toBeVisible()\n    await expect(\n      page.getByRole("menuitem", { name: "Mute local audio" })\n    ).toBeVisible()\n    await expect(\n      page.getByRole("menuitem", { name: "Set local volume…" })\n    ).toBeVisible()\n    await expect(\n      page.getByRole("menuitem", { name: "Clear upcoming" })\n    ).toBeVisible()\n'''
if old_menu_expect not in tests:
    raise SystemExit("existing menu regression anchor not found")
tests = tests.replace(old_menu_expect, new_menu_expect, 1)

insert_before = '''  test("supports slash-to-focus and Escape without losing the media draft", async ({\n'''
new_test = '''  test("keeps local audio and secondary actions explicit in the ellipsis menu", async ({\n    page,\n  }) => {\n    const modal = page.getByTestId("mqs-modal")\n    const actions = page.getByRole("button", { name: "Queue actions" })\n\n    await expect(modal).toHaveAttribute("data-local-muted", "false")\n    await expect(modal).toHaveAttribute("data-local-volume", "100")\n\n    await actions.click()\n    await expect(\n      page.getByRole("menuitem", { name: "Add pasted URL" })\n    ).toHaveCount(0)\n    await expect(\n      page.getByRole("menuitem", { name: "Play pasted URL next" })\n    ).toHaveCount(0)\n    await expect(\n      page.getByRole("menuitem", { name: "Load setlist" })\n    ).toBeVisible()\n    await page.getByRole("menuitem", { name: "Mute local audio" }).click()\n    await expect(modal).toHaveAttribute("data-local-muted", "true")\n\n    await actions.click()\n    await expect(\n      page.getByRole("menuitem", { name: "Unmute local audio" })\n    ).toBeVisible()\n    await page.getByRole("menuitem", { name: "Set local volume…" }).click()\n\n    const volumeDialog = page.getByRole("dialog", { name: "Local audio volume" })\n    await expect(volumeDialog).toContainText("this device only")\n    await expect(volumeDialog).toContainText("does not affect room volume")\n    const slider = page.getByRole("slider", { name: "Local audio volume" })\n    await expect(slider).toHaveValue("100")\n    await slider.fill("35")\n    await expect(page.getByTestId("local-volume-value")).toHaveText("35%")\n    await page.getByRole("button", { name: "Apply volume" }).click()\n    await expect(modal).toHaveAttribute("data-local-volume", "35")\n\n    const input = page.getByRole("textbox", { name: "Media URL" })\n    await input.fill("https://example.com/next")\n    await input.press("Escape")\n    await actions.click()\n    await expect(\n      page.getByRole("menuitem", { name: "Play pasted URL next" })\n    ).toBeVisible()\n    await expect(\n      page.getByRole("menuitem", { name: "Add pasted URL" })\n    ).toHaveCount(0)\n  })\n\n'''
if insert_before not in tests:
    raise SystemExit("secondary-actions test insertion anchor not found")
tests = tests.replace(insert_before, new_test + insert_before, 1)

page_path.write_text(page)
test_path.write_text(tests)
