import type { ChatMessage, Participant } from "./types"

const A = (n: number) => `${import.meta.env.BASE_URL}avatars/a${n}.png`

export const LOCAL_USER_ID = "you"

export const SEED_PARTICIPANTS: Participant[] = [
  {
    id: LOCAL_USER_ID,
    name: "You",
    avatar: A(2),
    chip: "rose",
    role: "host",
    isSpeaking: true,
    isMuted: false,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "jenny",
    name: "Jenny Wilson",
    avatar: A(1),
    chip: "rose",
    role: "host",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "eleanor",
    name: "Eleanor Pena",
    avatar: A(3),
    chip: "sky",
    role: "mod",
    isSpeaking: false,
    isMuted: false,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "floyd",
    name: "Floyd Miles",
    avatar: A(4),
    chip: "violet",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "jacob",
    name: "Jacob Jones",
    avatar: A(5),
    chip: "slate",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "courtney",
    name: "Courtney Henry",
    avatar: A(6),
    chip: "amber",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "jerome",
    name: "Jerome Bell",
    avatar: A(3),
    chip: "sky",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "brooklyn",
    name: "Brooklyn Simmons",
    avatar: A(1),
    chip: "rose",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "annette",
    name: "Annette Black",
    avatar: A(4),
    chip: "violet",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "darlene",
    name: "Darlene Robertson",
    avatar: A(5),
    chip: "slate",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "ralph",
    name: "Ralph Edwards",
    avatar: A(6),
    chip: "amber",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "jane",
    name: "Jane Cooper",
    avatar: A(2),
    chip: "sky",
    role: "speaker",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "cameron",
    name: "Cameron Williamson",
    avatar: A(1),
    chip: "amber",
    role: "listener",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: true,
  },
  {
    id: "kristin",
    name: "Kristin Watson",
    avatar: A(5),
    chip: "slate",
    role: "listener",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "wade",
    name: "Wade Warren",
    avatar: A(4),
    chip: "rose",
    role: "listener",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
  {
    id: "leslie",
    name: "Leslie Alexander",
    avatar: A(6),
    chip: "violet",
    role: "listener",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: true,
  },
  {
    id: "robert",
    name: "Robert Fox",
    avatar: A(2),
    chip: "sky",
    role: "listener",
    isSpeaking: false,
    isMuted: true,
    videoOn: false,
    raisedHand: false,
  },
]

export const SEED_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    userId: "jenny",
    name: "Jenny",
    body: "ipsum dolor sit amet.",
  },
  {
    id: "m2",
    userId: "eleanor",
    name: "Eleanor",
    body: "ipsum dolor sit amet.",
  },
  {
    id: "m3",
    userId: "floyd",
    name: "Floyd",
    body: "ipsum dolor sit amet simply dummy text... lalalalala",
  },
]
